In [1]:
!pip install pymongo

Requirement already satisfied: pymongo in c:\users\lenovo\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pymongo) (2.6.1)

In [2]:
!pip install streamlit_option_menu

Requirement already satisfied: streamlit_option_menu in c:\users\lenovo\anaconda3\lib\site-packages (0.3.13)
Requirement already satisfied: streamlit>=0.63 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit_option_menu) (1.30.0)
Requirement already satisfied: altair<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (4.2.2)
Requirement already satisfied: click<9,>=7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (8.1.7)
Requirement already satisfied: importlib-metadata<8,>=1.4 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (7.0.1)
Requirement already satisfied: numpy<2,>=1.19.3 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (1.26.4)
Requirement already satisfied: packaging<24,>=16.8 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (23.1)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.1.4)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (10.2.0)
Requirement already satisfied: protobuf<5,>=3.20 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (3.20.3)
Requirement already satisfied: pyarrow>=6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (14.0.2)
Requirement already satisfied: python-dateutil<3,>=2.7.3 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.8.2)
Requirement already satisfied: requests<3,>=2.27 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.31.0)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (13.3.5)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (8.2.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (4.9.0)
Requirement already satisfied: tzlocal<6,>=1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.1)
Requirement already satisfied: validators<1,>=0.2 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (0.18.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (3.1.37)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (6.3.3)
Requirement already satisfied: watchdog>=2.1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.1.6)
Requirement already satisfied: jinja2 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (3.1.3)
Requirement already satisfied: jsonschema>=3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (4.19.2)
Requirement already satisfied: toolz in c:\users\lenovo\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.12.0)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit>=0.63->streamlit_option_menu) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=0.63->streamlit_option_menu) (4.0.7)
Requirement already satisfied: zipp>=0.5 in c:\users\lenovo\anaconda3\lib\site-packages (from importlib-metadata<8,>=1.4->streamlit>=0.63->streamlit_option_menu) (3.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.3->streamlit>=0.63->streamlit_option_menu) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2024.2.2)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (2.15.1)
Requirement already satisfied: decorator>=3.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from validators<1,>=0.2->streamlit>=0.63->streamlit_option_menu) (5.1.1)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=0.63->streamlit_option_menu) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (0.1.0)

In [3]:
import pandas as pd 
import pymongo
import seaborn as sns 
import matplotlib.pyplot as plt 
import plotly.express as px 
import streamlit as st
import plotly.graph_objects as go
from streamlit_option_menu import option_menu

In [4]:

# connection to mongodb
client = pymongo.MongoClient("mongodb+srv://root:root@cluster.pghuhbt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster")
db = client['sample_airbnb']
col = db['listingsAndReviews']

In [16]:

clm = {'name': [], 'country': [], 'property_type': [], 'price': [], 'room_type': [],
   'bedrooms': [], 'beds': [],'accommodates':[],'cancellation_policy': [],'number_of_reviews': [],
   'minimum_nights': [], 'extra_people':[],'maximum_nights': [],'guests_include': [],'review_scores_cleanliness': [],
   'last_scraped': [], 'host_name':[], 'host_listings_count':[],'calendar_last_scraped': [], 
   'availability_365': [],'latitude': [], 'longitude': []}

for i in col.find():
    name = i.get('name')
    country = i['address'].get('country')
    property_type = i.get('property_type')
    price = i.get('price')
    room_type = i.get('room_type')
    
    accommodates = i.get('accommodates')
    minimum_nights = i.get('minimum_nights')
    maximum_nights = i.get('maximum_nights')
    cancellation_policy = i.get('cancellation_policy')
    number_of_reviews = i.get('number_of_reviews')
    
    bedrooms = i.get('bedrooms')
    beds = i.get('beds')
    guests_include = i.get('guests_included')
    extra_people = i.get('extra_people')
    review_scores_cleanliness = i['review_scores'].get('review_scores_cleanliness')
    last_scraped = i.get('last_scraped')
    
    host_name = i['host'].get('host_name')
    host_total_listings = i['host'].get('host_total_listings_count')
    calendar_last_scraped = i.get('calendar_last_scraped')
    availability_365 = i['availability'].get('availability_365')
    latitude = i['address']['location'].get('coordinates')[0]
    longitude = i['address']['location'].get('coordinates')[1]
    
    clm['name'].append(name)
    clm['country'].append(country)
    clm['property_type'].append(property_type)
    clm['price'].append(price)
    clm['room_type'].append(room_type)
    
    clm['accommodates'].append(accommodates)
    clm['minimum_nights'].append(minimum_nights)
    clm['maximum_nights'].append(maximum_nights)
    clm['number_of_reviews'].append(number_of_reviews)
    clm['cancellation_policy'].append(cancellation_policy)
    
    clm['bedrooms'].append(bedrooms)
    clm['beds'].append(beds)
    clm['guests_include'].append(guests_include)
    clm['extra_people'].append(extra_people)
    clm['review_scores_cleanliness'].append(review_scores_cleanliness)
    clm['last_scraped'].append(last_scraped)
    
    clm['host_name'].append(host_name)
    clm['host_listings_count'].append(host_total_listings)
    clm['availability_365'].append(availability_365)
    clm['calendar_last_scraped'].append(calendar_last_scraped)
    clm['latitude'].append(latitude)
    clm['longitude'].append(longitude)

df = pd.DataFrame(clm)

In [19]:
df['review_scores_cleanliness'] = df['review_scores_cleanliness'].fillna(0)
df['beds'] = df['beds'].fillna(1)
df['bedrooms'] = df['bedrooms'].fillna(1)
df['last_scraped'] = df['last_scraped'].dt.date
df['calendar_last_scraped'] = df['calendar_last_scraped'].dt.date
df.dropna(inplace=True)

In [20]:
df.head()

,name,country,property_type,price,room_type,bedrooms,beds,accommodates,cancellation_policy,number_of_reviews,...,maximum_nights,guests_include,review_scores_cleanliness,last_scraped,host_name,host_listings_count,calendar_last_scraped,availability_365,latitude,longitude
0,Charming Flat in Downtown Moda,Turkey,House,527.00,Entire home/apt,2.0,6.0,6,flexible,1,...,1125,1,10.0,2019-02-18,Zeynep,2,2019-02-18,362,29.031330,40.985850
1,Modern Spacious 1 Bedroom Loft,Canada,Apartment,50.00,Entire home/apt,1.0,2.0,4,flexible,0,...,1125,1,0.0,2019-03-11,Konstantin,1,2019-03-11,0,-73.591110,45.518890
2,Catete's Colonial Big Hause Room B,Brazil,House,250.00,Private room,1.0,8.0,8,strict_14_with_grace_period,1,...,1125,4,6.0,2019-02-11,Beatriz,5,2019-02-11,296,-43.180157,-22.926382
3,Ribeira Charming Duplex,Portugal,House,80.00,Entire home/apt,3.0,5.0,8,moderate,51,...,30,6,9.0,2019-02-16,Ana&Gonçalo,3,2019-02-16,239,-8.613080,41.141300
4,Apt Linda Vista Lagoa - Rio,Brazil,Apartment,701.00,Private room,1.0,1.0,2,flexible,0,...,1125,1,0.0,2019-02-11,Livia,1,2019-02-11,363,-43.205047,-22.971951

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   name                       5555 non-null   object
 1   country                    5555 non-null   object
 2   property_type              5555 non-null   object
 3   price                      5555 non-null   object
 4   room_type                  5555 non-null   object
 5   bedrooms                   5555 non-null   float64
 6   beds                       5555 non-null   float64
 7   accommodates               5555 non-null   int64
 8   cancellation_policy        5555 non-null   object
 9   number_of_reviews          5555 non-null   int64
 10  minimum_nights             5555 non-null   object
 11  extra_people               5555 non-null   object
 12  maximum_nights             5555 non-null   object
 13  guests_include             5555 non-null   object
 14  review_scores_cleanliness  5555 non-null   float64
 15  last_scraped               5555 non-null   object
 16  host_name                  5555 non-null   object
 17  host_listings_count        5555 non-null   int64
 18  calendar_last_scraped      5555 non-null   object
 19  availability_365           5555 non-null   int64
 20  latitude                   5555 non-null   float64
 21  longitude                  5555 non-null   float64
dtypes: float64(5), int64(4), object(13)
memory usage: 954.9+ KB

In [22]:
df.isnull().sum()

name                         0
country                      0
property_type                0
price                        0
room_type                    0
bedrooms                     0
beds                         0
accommodates                 0
cancellation_policy          0
number_of_reviews            0
minimum_nights               0
extra_people                 0
maximum_nights               0
guests_include               0
review_scores_cleanliness    0
last_scraped                 0
host_name                    0
host_listings_count          0
calendar_last_scraped        0
availability_365             0
latitude                     0
longitude                    0
dtype: int64

In [23]:
df.dtypes

name                          object
country                       object
property_type                 object
price                         object
room_type                     object
bedrooms                     float64
beds                         float64
accommodates                   int64
cancellation_policy           object
number_of_reviews              int64
minimum_nights                object
extra_people                  object
maximum_nights                object
guests_include                object
review_scores_cleanliness    float64
last_scraped                  object
host_name                     object
host_listings_count            int64
calendar_last_scraped         object
availability_365               int64
latitude                     float64
longitude                    float64
dtype: object

In [26]:
df['minimum_nights'] = df['minimum_nights'].astype(int)
df['maximum_nights'] = df['maximum_nights'].astype(int)
df['bedrooms'] = df['bedrooms'].astype(int)
df['beds'] = df['beds'].astype(int)
df['price'] = df['price'].astype(str).astype(float).astype(int)
df['extra_people'] = df['extra_people'].astype(str).astype(float).astype(int)
df['guests_include'] = df['guests_include'].astype(str).astype(int)

In [27]:
df.dtypes

name                          object
country                       object
property_type                 object
price                          int32
room_type                     object
bedrooms                       int32
beds                           int32
accommodates                   int64
cancellation_policy           object
number_of_reviews              int64
minimum_nights                 int32
extra_people                   int32
maximum_nights                 int32
guests_include                 int32
review_scores_cleanliness    float64
last_scraped                  object
host_name                     object
host_listings_count            int64
calendar_last_scraped         object
availability_365               int64
latitude                     float64
longitude                    float64
dtype: object

In [28]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
price,5555.0,2.787662e+02,8.422155e+02,9.00000,70.00000,129.00000,280.000000,4.884200e+04
bedrooms,5555.0,1.411341e+00,1.041547e+00,0.00000,1.00000,1.00000,2.000000,2.000000e+01
beds,5555.0,2.068947e+00,1.618592e+00,0.00000,1.00000,2.00000,3.000000,2.500000e+01
accommodates,5555.0,3.505851e+00,2.297019e+00,1.00000,2.00000,3.00000,4.000000,1.600000e+01
number_of_reviews,5555.0,2.760648e+01,4.979838e+01,0.00000,1.00000,5.00000,32.000000,5.330000e+02
minimum_nights,5555.0,5.564356e+00,2.261386e+01,1.00000,1.00000,2.00000,3.000000,1.250000e+03
extra_people,5555.0,2.279190e+01,6.933151e+01,0.00000,0.00000,0.00000,20.000000,2.346000e+03
maximum_nights,5555.0,1.382776e+06,5.256920e+07,1.00000,59.00000,1125.00000,1125.000000,2.147484e+09
guests_include,5555.0,1.747435e+00,1.487352e+00,1.00000,1.00000,1.00000,2.000000,1.600000e+01
review_scores_cleanliness,5555.0,6.845185e+00,4.216863e+00,0.00000,0.00000,9.00000,10.000000,1.000000e+01
host_listings_count,5555.0,1.440576e+01,6.584887e+01,0.00000,1.00000,2.00000,6.000000,1.198000e+03
availability_365,5555.0,1.731057e+02,1.398419e+02,0.00000,17.00000,171.00000,317.000000,3.650000e+02
latitude,5555.0,-6.623240e+00,9.052597e+01,-159.67869,-73.59953,-8.61142,29.019605,1.513390e+02
longitude,5555.0,2.206123e+01,2.809211e+01,-34.08829,20.72439,40.72713,41.162755,4.566563e+01

In [ ]:
import streamlit as st
import pandas as pd
import plotly.express as px
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
df.to_csv("airbnb_data.csv", index=False)

In [ ]:
#Streamlit page
st.set_page_config(layout= "wide")
st.markdown(f""" <style>.stApp {{
                    background: url('https://www.hotelnewsnow.com/Media/Default/Legacy/FeatureImages/20160209_STR_Airbnb_Feature_Headline1.jpg');   
                    background-size: cover}}
                 </style> """,unsafe_allow_html=True)

In [ ]:
option = st.sidebar.radio(":blue[Choose your page]", ["Home", "Data Visualization"])
    
if option == "Home":
    st.markdown("<h1 style='text-align: right; color: black;'>Airbnb Analysis</h1>", unsafe_allow_html=True)
    col1, col2 = st.columns(2)
    with col2:
        st.image("C:/Users/DELL/Pictures/1.webp",width=600)

In [ ]:
if option == 'Data Visualization':
    st.markdown("<h1 style='text-align: right; color: black;'>Airbnb Analysis</h1>", unsafe_allow_html=True)
    st.markdown("<h2 style='text-align: right; color: blue;'>Airbnb Property Type Visualization</h2>", unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    col3, col4 = st.columns(2)
    col5, col6 = st.columns(2)
    col7, col8 = st.columns(2)
    col9, col10 = st.columns(2)
    with col1:
        # Choose a country
        st.markdown('<h2 style="color: black;">Select a country</h2>', unsafe_allow_html=True)

        selected_country = st.selectbox("", df['country'].unique())
        
        # Filter data based on selected country
        filtered_df = df[df['country'] == selected_country]

In [ ]:
with col3:
        
        # Group by property type and sum the number_of_reviews
        property_reviews = filtered_df.groupby('property_type')['number_of_reviews'].sum().reset_index()

        # Sort the values by number_of_reviews in descending order
        property_reviews = property_reviews.sort_values(by='number_of_reviews', ascending=False)

        # Get top 10 property types
        top_10_property_reviews = property_reviews.head(10)

        # Plot countplot using Plotly
        fig = px.bar(top_10_property_reviews, 
                    x='property_type', 
                    y='number_of_reviews', 
                    color='property_type')
        fig.update_layout(title='Top 10 Property Types in {} by Number of Reviews'.format(selected_country),
                        xaxis_title='Property Type', 
                        yaxis_title='Number of Reviews')
        st.plotly_chart(fig, use_container_width=True)

In [ ]:
with col4:
        
        
        # Group by property type and calculate the mean review score for cleanliness
        property_cleanliness = filtered_df.groupby('property_type')['review_scores_cleanliness'].sum().reset_index()

        # Sort the values by mean review score in descending order
        property_cleanliness = property_cleanliness.sort_values(by='review_scores_cleanliness', ascending=False)

        # Get top 5 property types
        top_5_property_cleanliness = property_cleanliness.head(5)

        # Plot pie chart using Plotly
        fig = px.pie(top_5_property_cleanliness, 
                    values='review_scores_cleanliness', 
                    names='property_type',
                    title='Top 5 Property Types with Highest Review Scores for Cleanliness in {}'.format(selected_country))
        fig.update_traces(textposition='inside', textinfo='percent+label')
        st.plotly_chart(fig, use_container_width=True)

In [ ]:
 with col5:
        df_avg_price = df.groupby('property_type')['price'].mean().reset_index()
        df_avg_price = df_avg_price.sort_values(by='price', ascending=False).head(15)

        # Create a Plotly bar plot using the top 15 property types by average price
        fig = px.bar(
            df_avg_price,
            x='property_type',
            y='price',
            color='price',
            color_continuous_scale='viridis',
            title='Average Price by Property Type (Top 15)',
            labels={'property_type': 'Property Type', 'price': 'Average Price'}
        )

        # Customize the layout of the Plotly figure
        fig.update_layout(
            xaxis_title='Property Type',
            yaxis_title='Average Price',
            xaxis_tickangle=-45,
            coloraxis_colorbar=dict(title='Price', tickprefix='$')
        )

        # Render the Plotly figure in Streamlit
        st.plotly_chart(fig, use_container_width=True)

In [ ]:
 with col6:
        # Aggregate data by country
        country_agg = df.groupby('country').agg({'price': 'mean'}).reset_index()

        # Create choropleth map
        fig = px.choropleth(country_agg, 
                            locations='country', 
                            locationmode='country names',
                            color='price', 
                            hover_name='country',
                            color_continuous_scale='Viridis',
                            title='Average Price by Country')
        st.plotly_chart(fig)

In [ ]:
 with col8:
        col1, col2 = st.columns(2)
        with col1:
            # Define the desired price range for the slider (0 to 3000)
            price_min = 0
            price_max = 3000

            # User input for price range
            st.markdown('<h2 style="color: black;">Select a price range</h2>', unsafe_allow_html=True)
            price_range = st.slider("Select price range", price_min, price_max, (price_min, price_max))

            # Filter the DataFrame based on the selected price range
            filtered_df = df[(df['price'] >= price_range[0]) & (df['price'] <= price_range[1])]

In [ ]:
 with col7:
        
        # User input for the number of beds, bedrooms, and cancellation policy
        st.markdown('<h2 style="color: black;">Choose additional filters</h2>', unsafe_allow_html=True)
        col3, col4 ,col5= st.columns(3)
        with col3:
            selected_beds = st.selectbox("Number of beds", options=sorted(filtered_df['beds'].unique()))
        with col4:
            selected_bedrooms = st.selectbox("Number of bedrooms", options=sorted(filtered_df['bedrooms'].unique()))
        with col5:
            selected_cancellation_policy = st.selectbox("Cancellation policy", options=filtered_df['cancellation_policy'].unique())

In [ ]:

    with col9:
        # Filter the DataFrame based on the user's selections
        filtered_df = filtered_df[
        (filtered_df['beds'] == selected_beds) &
        (filtered_df['bedrooms'] == selected_bedrooms) &
        (filtered_df['cancellation_policy'] == selected_cancellation_policy)]

In [ ]:
# Find the top 10 apartment names based on the filtered DataFrame
        top_10_names = filtered_df['name'].value_counts().head(10).index

        # Filter the DataFrame to include only the top 10 names
        filtered_top_10_df = filtered_df[filtered_df['name'].isin(top_10_names)]

        # Truncate apartment names to a specified length (e.g., 15 characters)
        max_name_length = 15
        filtered_top_10_df['name_truncated'] = filtered_top_10_df['name'].apply(lambda x: x[:max_name_length] + '...' if len(x) > max_name_length else x)

        # Plot the bar plot of the top 10 apartment names within the selected filters using truncated names
        fig = px.bar(
            filtered_top_10_df,
            x='name_truncated',
            y='price',
            title=f'Top 10 Apartment Names within Selected Filters',
            labels={'name_truncated': 'Apartment Name', 'price': 'Price'},
            hover_data=['name','number_of_reviews', 'review_scores_cleanliness']
        )

        # Customize layout and display the Plotly chart in Streamlit
        fig.update_layout(
            xaxis_title='Apartment Name',
            yaxis_title='Price'
        )
        st.plotly_chart(fig, use_container_width=True)

In [ ]:
def data():
    col = {'name': [], 'country': [], 'property_type': [], 'price': [], 'room_type': [],
           'bedrooms': [], 'beds': [],'accommodates':[],'cancellation_policy': [],'number_of_reviews': [],
           'minimum_nights': [], 'extra_people':[],'maximum_nights': [],'guests_include': [],'review_scores_cleanliness': [],
           'last_scraped': [], 'host_name':[], 'host_listings_count':[],'calendar_last_scraped': [], 
           'availability_365': [],'latitude': [], 'longitude': []}

    for i in clm.find():
        name = i.get('name')
        country = i['address'].get('country')
        property_type = i.get('property_type')
        price = i.get('price')
        room_type = i.get('room_type')

        accommodates = i.get('accommodates')
        minimum_nights = i.get('minimum_nights')
        maximum_nights = i.get('maximum_nights')
        cancellation_policy = i.get('cancellation_policy')
        number_of_reviews = i.get('number_of_reviews')

        bedrooms = i.get('bedrooms')
        beds = i.get('beds')
        guests_include = i.get('guests_included')
        extra_people = i.get('extra_people')
        review_scores_cleanliness = i['review_scores'].get('review_scores_cleanliness')
        last_scraped = i.get('last_scraped')
        
        host_name = i['host'].get('host_name')
        host_total_listings = i['host'].get('host_total_listings_count')
        calendar_last_scraped = i.get('calendar_last_scraped')
        availability_365 = i['availability'].get('availability_365')
        latitude = i['address']['location'].get('coordinates')[0]
        longitude = i['address']['location'].get('coordinates')[1]

        clm['name'].append(name)
        clm['country'].append(country)
        clm['property_type'].append(property_type)
        clm['price'].append(price)
        clm['room_type'].append(room_type)

        clm['accommodates'].append(accommodates)
        clm['minimum_nights'].append(minimum_nights)
        clm['maximum_nights'].append(maximum_nights)
        clm['number_of_reviews'].append(number_of_reviews)
        clm['cancellation_policy'].append(cancellation_policy)

        clm['bedrooms'].append(bedrooms)
        clm['beds'].append(beds)
        clm['guests_include'].append(guests_include)
        clm['extra_people'].append(extra_people)
        clm['review_scores_cleanliness'].append(review_scores_cleanliness)
        clm['last_scraped'].append(last_scraped)
        
        clm['host_name'].append(host_name)
        clm['host_listings_count'].append(host_total_listings)
        clm['availability_365'].append(availability_365)
        clm['calendar_last_scraped'].append(calendar_last_scraped)
        clm['latitude'].append(latitude)
        clm['longitude'].append(longitude)

    df = pd.DataFrame(clm)
    #data cleaning
    df['review_scores_cleanliness'] = df['review_scores_cleanliness'].fillna(0)
    df['beds'] = df['beds'].fillna(1)
    df['bedrooms'] = df['bedrooms'].fillna(1)
    df['last_scraped'] = df['last_scraped'].dt.date
    df['calendar_last_scraped'] = df['calendar_last_scraped'].dt.date
    df.dropna(inplace=True)
    return df